In [80]:
import torch 
from torch import nn 
from torch.nn.init import xavier_uniform_
import numpy as scinp
from pennylane import numpy as np 

In [81]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print("Using {} device".format(device))

Using cuda:0 device


In [107]:
class Critic(nn.Module):

    def __init__(self, data_dimension, hidden_dimensionality=None):
        super(Critic, self).__init__()

        if hidden_dimensionality is None:
            hidden_dimensionality = [16, 8]

        self.layer_dimensions = [data_dimension] + hidden_dimensionality + [1]

        layers = []

        for i in range(len(self.layer_dimensions) - 1):
            in_dim = self.layer_dimensions[i]
            out_dim = self.layer_dimensions[i + 1]
            linear_layer = nn.Linear(in_dim, out_dim)
            xavier_uniform_(linear_layer.weight)
            layers.append(linear_layer)
        self.network = nn.Sequential(*layers)

    def forward(self, x):
        critic_output = self.network(x)
        return critic_output


In [108]:
critic=Critic(4).to(device)
critic

Critic(
  (network): Sequential(
    (0): Linear(in_features=4, out_features=16, bias=True)
    (1): Linear(in_features=16, out_features=8, bias=True)
    (2): Linear(in_features=8, out_features=1, bias=True)
  )
)

In [109]:
X_minibatch=torch.Tensor(4,4).uniform_(0,1).to(device)
X_minibatch.requires_grad=True
X_minibatch

tensor([[0.7185, 0.0412, 0.2561, 0.5148],
        [0.1854, 0.8202, 0.8364, 0.7543],
        [0.1910, 0.4498, 0.2355, 0.3210],
        [0.4180, 0.8283, 0.9194, 0.8446]], device='cuda:0', requires_grad=True)

In [110]:
for i in range(len(X_minibatch)):
    X_i=X_minibatch[i]
    y_i=critic(X_i)
    print(torch.autograd.grad(outputs=y_i,inputs=X_i))

(tensor([0.0146, 0.0961, 0.1770, 0.2701], device='cuda:0'),)
(tensor([0.0146, 0.0961, 0.1770, 0.2701], device='cuda:0'),)
(tensor([0.0146, 0.0961, 0.1770, 0.2701], device='cuda:0'),)
(tensor([0.0146, 0.0961, 0.1770, 0.2701], device='cuda:0'),)


In [113]:
B=scinp.random.uniform(-1,1,size=(4,4))
B

array([[ 0.91235996, -0.32094347, -0.88413547,  0.74381247],
       [ 0.96290347,  0.02159079,  0.17826059,  0.32000543],
       [-0.19383135, -0.38087511, -0.95024166, -0.19886284],
       [ 0.70306431,  0.41781422,  0.48008937, -0.79094579]])

In [117]:
B[[0,3]]

array([[ 0.91235996, -0.32094347, -0.88413547,  0.74381247],
       [ 0.70306431,  0.41781422,  0.48008937, -0.79094579]])

In [122]:
type(B[np.random.choice(4,size=2)])

numpy.ndarray

In [123]:
def sample_arrays(X, batch_size, device):

    # We sample n=batch_size points from the data
    row_indices = np.random.choice(len(X), size=batch_size)
    X_minibatch = X[row_indices]
    X_minibatch = torch.Tensor(X_minibatch).to(device)

    # We sample n=batch_size points from the generator
    
    row_indices = np.random.choice(len(X), size=batch_size)
    z_minibatch = X[row_indices]
    z_minibatch = torch.Tensor(z_minibatch).to(device)
    
    # We sample n=batch_size noise points
    epsilons = torch.Tensor(batch_size).uniform_(0, 1).to(device)
    return X_minibatch, z_minibatch, epsilons


In [173]:
X_minibatch, z_minibatch, epsilons=sample_arrays(B,2,device)

In [174]:
epsilons=torch.Tensor(np.ones(2)*10).to(device)
epsilons=epsilons[:,np.newaxis]
epsilons

tensor([[10.],
        [10.]], device='cuda:0')

In [175]:
diff=X_minibatch-z_minibatch
diff

tensor([[ 0.0505,  0.3425,  1.0624, -0.4238],
        [ 0.8969,  0.7987,  1.4303, -0.5921]], device='cuda:0')

In [176]:
epsilons*diff

tensor([[ 0.5054,  3.4253, 10.6240, -4.2381],
        [ 8.9690,  7.9869, 14.3033, -5.9208]], device='cuda:0')

In [142]:
X = torch.Tensor([[3, 5],[5, 5],[1, 0]])                                                                                                                                                                          
y = torch.Tensor([7,4])                                                                                                                                                                                   
X*y

tensor([[21., 20.],
        [35., 20.],
        [ 7.,  0.]])